### ISSUE TITLE
Keybind witht the original split 

### ISSUE THREAD

**Issue by kithokit** [ilgarm/terminator_plugins#1]
I suggest to keybind with the original split

say if i click ctrl+shift+o

then it will check if there is ssh session already

if not, then use the original split, 
if yes then use your clone split.

**Comment by ilgarm** [comment]
@kithokit yes that makes sense, I will look into it and update, thx for the idea!

**Comment by ilgarm** [comment]
unlikely to happen, as I am not working on this repo for years
